### ISSUE TITLE
Wrong height when string contains trailing "\n"

### ISSUE THREAD

**Issue by d6u** [Krelborn/KILabel#18]
![image](https://cloud.githubusercontent.com/assets/2153667/7558335/da8c5fdc-f76f-11e4-98ed-8edd05ff16ac.png)

The left string was `I ♥ that #RainbowStarDay came back for week 2\n\nhttp://t.co/Am1qlGaYyP\n`. `lineSpacing` is `10` for KILabel.

When you do https://github.com/Krelborn/KILabel/blob/master/KILabel/Source/KILabel.m#L550, the `textBounds` was incorrectly missing the last empty line, but including line spacing.

**Comment by Krelborn** [comment]
Looks like there's a simple fix for this which is to use usedRectForTextContainer: to calculate the bounds from the layout manager. The method currently used is giving the smallest possible bounds which excludes whitespace.

**Comment by Krelborn** [comment]
Fixed in the develop branch. Point your Podspec at the branch to try it out.
<pre>
pod 'KILabel', :branch: 'develop'
</pre>
I will do an official 1.0.1 bugfix release for this relatively soon.

**Comment by d6u** [comment]
This fixed the issue. Thanks! I really like your library here. I tried [TTTAttributedLabel](https://github.com/TTTAttributedLabel/TTTAttributedLabel) before but it renders text differently when contains emoji or CJK characters. It would be really nice to add customized "links" other than just hashtag, mention, and urls. Great work!

**Comment by Krelborn** [comment]
No problem, thanks for the feedback.

If you want custom links have a look at the feature branch for issue #16 . It should be exactly what you want, would appreciate some feedback on that if you have any.
<pre>
pod 'KILabel', :branch: 'feature/link-classifiers'
</pre>
