### ISSUE TITLE
'NSRangeException', reason: 'NSMutableRLEArray objectAtIndex:effectiveRange:: Out of bounds'

### ISSUE THREAD

**Issue by guodongyangwen** [Krelborn/KILabel#19]
it will crash when i touch the "@username"   sometimes,but I print the selectedRange   and it's right

**Comment by Krelborn** [comment]
Could you give me a bit more information.
Is this the 1.0 version or one of the dev branches? 
Is there a particular string giving you a crash? 
How is the label configured? 
what's the line of code in KILabel throwing the exception?

Thanks.

**Comment by Krelborn** [comment]
Closing this issue as I can't currently reproduce it without further information. Happy to look at it in the future if I can get a reproducible test case.
