### ISSUE TITLE
KILinkTapHandler only working when Activate Breakpoints

### ISSUE THREAD

**Issue by wilferrel** [Krelborn/KILabel#44]
I literally copied and pasted the KILabelTableViewController into my project I can see the tableview and hash tags I can also see the shadow highlighting effect on hashtage but never reaches call back until I Activate Breakpoint. Has anyone had this issue?

**Comment by wilferrel** [comment]
Closing issue, I figured it out. I had a UITapGestureRecognizer on view that was interfering with label. All I needed to do was add     [tap setCancelsTouchesInView:NO]; It was hard to initially see because I had added that to Base View Controller. anyways thanks for control.

**Comment by VansonLeung** [comment]
Me too +1
