### ISSUE TITLE
UITableViewCells tap not getting recognised when used along with a UIGestureRecogniser

### ISSUE THREAD

**Issue by genaks** [Krelborn/KILabel#73]
I am using KILabels in my UITableViewCells where I need to make the hashtags and usernames tappable. I also need the UITableViewCells to show options to the user either by swiping the cell to the left or by long pressing on the UITableViewCell. The thing is the KILabel is not catching the taps when used along with the swipe options or with the long press UIGestureRecogniser.

**Comment by HackShitUp** [comment]
@genaks were you able to solve this? I have a similar issue with this as well...

**Comment by genaks** [comment]
@HackShitUp You can follow the Guferos' comment from [here](https://github.com/Krelborn/KILabel/issues/57) to solve this issue.

**Comment by HackShitUp** [comment]
@genaks awesome, thank you so much! :)

**Comment by genaks** [comment]
@HackShitUp most welcome.
