### ISSUE TITLE
Click Not working in UITableViewCell

### ISSUE THREAD

**Issue by Mahan3340** [Krelborn/KILabel#79]
Followed instruction on and tap its not working in UITableViewCell , swift 4

**Comment by satya-p91** [comment]
hi @Mahan3340 I am having the same issue. Did you found any solution for this?

**Comment by Mahan3340** [comment]
@satya-p91 I guess there was sth wrong with my code at that time. I think I was using a UITapGestureRecognizer somewhere but I don't quite remember as I used it years ago. This is a pretty old repo so I think you can also clone the project and add the code manually to modify and debug it; I remember doing this a lot when I was looking for a similar library at that time.

**Comment by satya-p91** [comment]
@Mahan3340 Okay Thanks!
