### ISSUE TITLE
Create example using UITableView 

### ISSUE THREAD

**Issue by songhanghang** [Krelborn/KILabel#9]
- (void)touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event
{
    self.isTouchMoved = NO;
    
    // Get the info for the touched link if there is one
    NSDictionary *touchedLink;
    CGPoint touchLocation = [[touches anyObject] locationInView:self];
    touchedLink = [self getLinkAtLocation:touchLocation];
    
    if (touchedLink)
    {
        self.selectedRange = [[touchedLink objectForKey:@"range"] rangeValue];
    }
    else
    {
        [super touchesBegan:touches withEvent:event];
    }
}

this method can not come in,I think may be touch Event is can not catch,But I can not solve issue

**Comment by Krelborn** [comment]
Will expand the demo application to show example working in a table.

Example will demonstrate:
* Responding to tappable links
* Sizing of table rows.

**Comment by Krelborn** [comment]
There is now a simple example of KILabel working in a UITableView. Row sizing is dynamic and touches work as expected. Will be included in 1.0.0 release.

**Comment by songhanghang** [comment]
thanks
